### ISSUE TITLE
[2004 PC version] Editing weapon/item descriptions breaks text alignment

### ISSUE THREAD

**Issue by ViperAcidZX** [DeveloperJose/Mega-Man-X8-Asset-Manager#3]
I am having an annoying problem where trying to make a single change to the SUB_TXT.mcb file with this editor breaks the text alignment of the weapon and item descriptions and also causes them to appear at the top of the screen instead of the text box in the sub-menu. I keep getting some annoying parsing errors that I'm not sure why it keeps popping up but it always pops up every time when changing between different text strings. Can you please look into what is causing these problems? I want to try and correct the inputs of Zero's moves/X's Shoryuken and some other things. I am using the latest version available on the Releases page.

**Comment by rainfallpianist** [comment]
I'll try to look into it this weekend. Could you give me more details about these "parsing errors"? If you could take some screenshots of that and your problem and attach them to a reply here that would help me figure it out faster.

**Comment by ViperAcidZX** [comment]
I've been getting errors like this when trying to edit the weapon descriptions in the pause menu. I'm not sure if I'm missing something or how to install them other than Python (which I have installed the latest version available at the moment).

![MegaManX8_Text_Editor-2021_08_10_18-15-12](https://user-images.githubusercontent.com/19318128/128942127-1828db4b-4d68-4bde-b637-7e4b0543c06d.png)
![MegaManX8_Text_Editor-2021_08_10_18-15-18](https://user-images.githubusercontent.com/19318128/128942128-8edcd96f-05ef-48be-a580-a2afb0eb6544.png)
![MegaManX8_Text_Editor-2021_08_10_18-15-27](https://user-images.githubusercontent.com/19318128/128942129-435c75d3-023f-4c5c-b343-c657f45d4802.png)
![MegaManX8_Text_Editor-2021_08_10_18-15-49](https://user-images.githubusercontent.com/19318128/128942130-5fd54077-781e-4256-b60d-f71de1221347.png)

**Comment by rainfallpianist** [comment]
Fixed by 14eb5237dcc16987b54462ecf4e9e4764e3cc7d4 in the new version release (v2.1) which can be found in the releases here https://github.com/rainfallpianist/Python-RockManX8/releases/
